NoiThat/Controllers/KhachhangController.cs
using Facebook;
using GoogleAuthentication.Services;
using Newtonsoft.Json;
using NoiThat.DAO;
using NoiThat.Library;
using NoiThat.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Xml.Linq;

namespace NoiThat.Controllers
{
    public class KhachhangController : Controller
    {
        // GET: Khachhang
        UserDAO userDAO = new UserDAO();
        OrderDAO orderDAO = new OrderDAO();
        OrderDetailDAO detailDAO=new OrderDetailDAO();
        ProductDAO productDAO = new ProductDAO();
        public ActionResult DangNhap()
        {
            ViewBag.Error = "";
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = "1246301172713746",
                redirect_uri = "https://localhost:44346/Khachhang/FacebookRedirect",
                scope = "public_profile,email"
            });
            ViewBag.Url = loginUrl;

            var ClientID = "679615721941-oea3muamldbssq6ccg57d1m4b27v6ddf.apps.googleusercontent.com";
            var url = "https://localhost:44346/Khachhang/GoogleLoginCallback";
            var response = GoogleAuth.GetAuthUrl(ClientID, url);
            ViewBag.response = response;

            return View();
        }

        public async Task<ActionResult> GoogleLoginCallback(string code)
        {

            var ClientSecret = "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";
            var ClientID = "679615721941-oea3muamldbssq6ccg57d1m4b27v6ddf.apps.googleusercontent.com";
            var url = "https://localhost:44346/Khachhang/GoogleLoginCallback";
            var token = await GoogleAuth.GetAuthAccessToken(code, ClientID, ClientSecret, url);
            var userProfile = await GoogleAuth.GetProfileResponseAsync(token.AccessToken.ToString());
            var googleUser = JsonConvert.DeserializeObject<GoogleProfile>(userProfile);

            User user = new User();
            user.FullName = googleUser.Name;
            user.Email = googleUser.Email;
            user.Phone = "0359258471";
            user.Address = googleUser.Locate;
            user.UserName = googleUser.Email;
            user.Password = googleUser.Email;
            user.Img = "avt_0.jpg";
            user.Status = 1;
            user.CreatedAt = DateTime.Now;
            if (userDAO.Insert(user) == 1)
            {
                Session["UserCustomer"] = user.UserName;
                Session["UserId"] = user.id;
                Session["FullName"] = user.FullName;
                Session["Img"] = user.Img;
                Session["Phone"] = user.Phone;
                Session["Address"] = user.Address;
                Session["Email"] = user.Email;
                return Redirect("~/");
            }


            return View();
        }

        public ActionResult FacebookRedirect(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Get("/oauth/access_token", new
            {
                client_id = "1246301172713746",
                client_secret = "0d3c35b770c86e68aaacc20df7816cf3",
                redirect_uri = "https://localhost:44346/Khachhang/FacebookRedirect",
                code = code
            });

            fb.AccessToken = result.access_token;
            dynamic me = fb.Get("/me?fields=name,email");
            string name = me.name;
            string email = me.email;
            string phone = "0359258471";
            int status = 1;
            
            using (var dbContext = new NoiThatDBContext())
            {
                var user = new User
                {
                    FullName = name,
                    Email = email,
                    Phone = phone,
                    UserName = email,
                    Password = email,
                    Status = status,
                    Img = "avt_0.jpg",
                    CreatedAt = DateTime.Now
                };
                dbContext.Users.Add(user);
                dbContext.SaveChanges();
                Session["UserCustomer"] = user.UserName;
                Session["UserId"] = user.id;
                Session["FullName"] = user.FullName;
                Session["Img"] = user.Img;
                Session["Phone"] = user.Phone;
                Session["Address"] = user.Address;
                Session["Email"] = user.Email;
            }
            return Redirect("~/");

        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection filled)
        {
            String username = filled["username"];
            String password = filled["password"];
            User rowUser = userDAO.getRow(username);
            String strError = "";
            if (rowUser == null)
            {
                strError = "Tên đăng nhập không đúng";
            }
            else
            {
                if (password.Equals(rowUser.Password))
                {
                    Session["UserCustomer"] = username;
                    Session["UserId"] = rowUser.id;
                    Session["FullName"] = rowUser.FullName;
                    Session["Img"] = rowUser.Img;
                    Session["Phone"] = rowUser.Phone;
                    Session["Address"] = rowUser.Address;
                    Session["Email"] = rowUser.Email;
                    return Redirect("~/");
                }
                else
                {
                    strError = "Sai mật khẩu";
                }
            }
            ViewBag.Error = "<span class='text-danger>'" + strError + "</div>";
            return View("DangNhap");
        }

        public ActionResult DangKy()
        {
            ViewBag.Error = "";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangKy(User user, FormCollection filled)
        {
            String strError = "";
            List<User> list = userDAO.getList();
            if (ModelState.IsValid)
            {
                foreach (var item in list)
                {
                    if (user.UserName.Equals(item.UserName))
                    {
                        strError = "Tên đăng nhập đã tồn tại";
                    }
                    else
                    {
                        if (user.Email.Equals(item.Email))
                        {
                            strError = "Email đã tồn tại";
                        }
                        else
                        {
                            if (!filled["RePassword"].Equals(user.Password))
                            {
                                strError = "Nhập lại mật khẩu không đúng";
                            }
                            else
                            {
                                if (!XString.chkMK(user.Password))
                                {
                                    strError = "Mật khẩu phải có ít nhất 6 ký tự, một số, một ký tự in hoa và một ký tự đặc biệt";
                                }
                                else
                                {
                                    //upload file
                                    user.Img = "abc";
                                    //end upload file
                                    user.Status = 1;
                                    user.CreatedAt = DateTime.Now;
                                    Session["UserCustomer"] = user.UserName;
                                    Session["UserId"] = user.id;
                                    Session["FullName"] = user.FullName;
                                    Session["Img"] = user.Img;
                                    Session["Phone"] = user.Phone;
                                    Session["Address"] = user.Address;
                                    Session["Email"] = user.Email;
                                    userDAO.Insert(user);
                                    return Redirect("~/");
                                }
                            }
                        }
                    }

                }
                
            }

            //String strError = "";
            //User user = new User();
            //
            //user.FullName = filled["FullName"];
            //user.UserName = filled["UserName"];
            //user.Password = filled["Password"];
            //user.Email = filled["Email"];
            //user.Phone = filled["Phone"];
            //user.Address = filled["Address"];
            //user.Status = 1;


            ViewBag.Error = "<p class=\"login-box-msg text-danger\">" + strError + "</strong></p>";
            return View(user);
        }

        public ActionResult DangXuat()
        {
            Session["UserCustomer"] = "";
            Session["UserId"] = "";
            Session["FullName"] = "";
            Session["Img"] = "";
            Session["Phone"] = "";
            Session["Address"] = "";
            Session["Email"] = "";
            return Redirect("~/dang-nhap");
        }

        public ActionResult DonHangCaNhan()
        {
            ViewBag.DonHangCaNhan = orderDAO.getListByUserId(Convert.ToInt32(Session["UserId"]));
            return View("DonHangCaNhan");
        }


        public ActionResult ThongTinCaNhan()
        {
            int id = int.Parse(Session["UserId"].ToString());
            User user = userDAO.getRow(id);
            return View(user);
        }

        public ActionResult ChinhSuaThongTin(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = userDAO.getRow(id);
            if (user == null)
            {
                return HttpNotFound();

NoiThat/Views/Khachhang/ChinhSuaThongTin.cshtml
@model NoiThat.Models.User

@{
    ViewBag.Title = "ChinhSuaThongTin";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}


<h2>Chỉnh Sửa Thông Tin</h2>

@using (Html.BeginForm("ChinhSuaThongTin", "Khachhang", FormMethod.Post))

{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.id)
    @Html.HiddenFor(model => model.UserName)
    @Html.HiddenFor(model => model.Password)
    @Html.HiddenFor(model => model.Img)
    @Html.HiddenFor(model => model.Status)

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ThongTinCaNhan")
</div>

<style>
    /* Căn giữa phần tử h2 */
    h2 {
        text-align: center;
        margin-top: 40px;
        margin-bottom: 30px;
        font-size: 28px;
    }

    /* Định dạng form */
    .form-horizontal {
        max-width: 600px;
        margin: 0 auto;
    }

    /* Định dạng label và input */
    .control-label {
        font-weight: bold;
    }

    /* Định dạng các form group */
    .form-group {
        margin-bottom: 20px;
    }

    /* Định dạng nút Save */
    .btn-default {
        padding: 10px 20px;
        border-radius: 4px;
        background-color: #007bff;
        color: #fff;
        border: none;
        cursor: pointer;
    }

    /* Định dạng link Back to List */
    a {
        display: block;
        text-align: center;
        margin-top: 20px;
        text-decoration: none;
        color: #007bff;
    }

    /* Định dạng validation summary */
    .text-danger {  
        color: red;
        font-size: 14px;
        text-align: center;
    }
    body {
        background-image: url('/Content/images/Pic/back-5.jpg'); /* Đường dẫn tới hình ảnh */
        background-size: cover; /* Đảm bảo hình ảnh sẽ được kích thước phù hợp với kích thước trình duyệt */
        background-position: center; /* Căn hình ảnh vào giữa trang */
        background-repeat: no-repeat; /* Không lặp lại hình ảnh nền */
    }
    .container {
        background-color: rgba(255, 255, 255, 0.9); /* Điều chỉnh màu nền cho phần nội dung */
        padding: 20px; /* Tạo khoảng cách giữa nội dung và viền */
    }


</style>

NoiThat/Views/Khachhang/DangKy.cshtml
@model NoiThat.Models.User
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

@using (Html.BeginForm("DangKy", "Khachhang", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">

        <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
            <article style="background-color: floralwhite;" class="card-body">
                <header class="mb-4"><h4 class="card-title">Đăng Ký</h4></header>
                <form>
                    @Html.ValidationSummary("", new { @class = "text-danger" })
                    @Html.AntiForgeryToken()
                    @Html.Raw(ViewBag.Error)

                    <div class="form-group">
                        <label>Tên đăng nhập</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Mật khẩu</label>
                        <div class="col-md-10">
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Nhập lại mật khẩu</label>
                        <div class="col-md-10">
                            <input class="form-control" name="RePassword" type="password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Họ và tên</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 col-form-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Điện thoại</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Địa chỉ</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Giới tính</label>
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Gender, new[] { new SelectListItem { Text = "Nữ", Value = "2" }, new SelectListItem { Text = "Nam", Value = "1" } }, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                        </div>

                    </div>
                    <div class="form-group">
                        <button style= "background-color:burlywood" type="submit" class="btn btn-primary btn-block"> Đăng ký  </button>
                    </div> <!-- form-group// -->

                </form>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        <p style="color:white" class="text-center mt-4">Đã có tài khoản? <a style="color:white" href="~/dang-nhap"> Tới đăng nhập</a></p>
        <br><br>
    </section>
}
<video autoplay muted loop id="myVideo" style="position: fixed; right: 0; bottom: 0; min-width: 100%; min-height: 100%;">
    <source src="~/Content/images/demo.mp4" type="video/mp4">
</video>
<style>
    #myVideo {
        z-index: -1;
    }
</style>

NoiThat/Views/Khachhang/DangNhap.cshtml
@{
    ViewBag.Title = "Đăng nhập";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@using (Html.BeginForm("DangNhap", "Khachhang", FormMethod.Post))
{
    <section class="section-conten padding-y" style="min-height:84vh">
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
            <div style=" background-color: floralwhite;" class="card-body">
                <h4 class="card-title mb-4">Đăng nhập</h4>
                <form>
                    <div class="form-group">
                        <input name="username" class="form-control" placeholder="Tên đăng nhập" type="text">
                    </div>
                    <div class="form-group">
                        <input name="password" class="form-control" placeholder="Mật khẩu" type="password">
                    </div>
                    <div class="form-group">
                        <button style="background-color:burlywood" type="submit" class="btn btn-primary btn-block">Login</button>
                    </div>

                    <a href="@ViewBag.Url" class="btn btn-custom" style="background-color: #1877f2;">
                        <img src="~/Content/images/Pic/fb-2.jpg" style="vertical-align: middle; margin-right: 7px; "> Login With Facebook
                    </a>

                    <a style="font-family: Arial; font-size: 16px; margin-left: 5px;"></a>

                    <a href="@ViewBag.response" class="btn btn-custom" style="background-color: #FF4900; margin-top: 3px;">

                        <img src="~/Content/images/Pic/gg-5.jpg" style="vertical-align: middle; margin-right: 5px;">Login With Google
                    </a>

                    @Html.Raw(ViewBag.Error)
                </form>
            </div>
        </div>
        <p style="color:white;" class="text-center mt-4">Không có tài khoản? <a style="color:white;" href="~/dang-ky"> Đăng ký ngay!</a></p>
    </section>
}

<style>
    .btn {
        transition: transform 0.3s ease;
        border-radius: 20px;
        padding: 10px 20px;
        font-size: 15px;
        text-align: center;
        text-decoration: none;
        color: #fff;
        cursor: pointer;
        display: inline-block;
    }

    .btn-custom {
        width: 100%;
        margin-bottom: 10px; /* Khoảng cách giữa các nút */
        position: relative; /* Thêm vào để điều chỉnh kích thước chữ */
    }


        .btn-custom img {
            height: 25px; /* Điều chỉnh kích thước của hình ảnh */
            vertical-align: middle;
            margin-right: 5px;
            margin-top: -5px;
        }

    .btn:hover {
        transform: scale(1.1);
    }
</style>

@*<video autoplay muted loop id="myVideo" style="margin-top:300px; position: fixed; right: 0; bottom: 0; min-width: 100%; min-height: 100%;">
        <source src="~/Content/images/prime.mp4" type="video/mp4">
    </video>*@
<video autoplay muted loop id="myVideo">
    <source src="~/Content/images/Zed.mp4" type="video/mp4">
</video>


<style>
    #myVideo {
        position: fixed;
        right: 0;
        bottom: 0;
        min-width: 100%;    
        min-height: 100%;
        z-index: -1; /* Đưa video xuống layer dưới cùng */
    }
    .layout-container {
        /* Đặt các thuộc tính CSS cho layout của bạn ở đây */
        /* Ví dụ: */
        width: 80%;
        margin: auto;
        /* Các thuộc tính khác */
</style>

NoiThat/Views/Khachhang/DonHangCaNhan.cshtml
@{
    ViewBag.Title = "DonHangCaNhan";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<link href="~/Public/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />

@using NoiThat.Models;
@using NoiThat.DAO;
@{ OrderDetailDAO orderDetailDAO = new OrderDetailDAO();}
<div class="card mt-3">
    <h5 class="card-header">Đơn hàng của <a style="color:forestgreen">@Session["FullName"]</a> </h5>
    <div class="card-body">

        @Html.Raw(ViewBag.ThongBao)


        <table id="Panigation" class="table table-bordered table-hover table-sm mb-0">
            <thead>
                <tr style="text-align:center;">
                    <th class="col-md-1">Mã đơn hàng</th>
                    <th class="col-md-3">Thời gian đặt</th>
                    <th class="col-md-3">Tổng tiền</th>
                    <th class="col-md-3">Tình Trạng</th>
                    <th class="col-md-2" style="text-align:left;" >Hành Động</th>
                </tr>
            </thead>
        </table>
        @foreach (Order item in @ViewBag.DonHangCaNhan)
        {
            <div class="row" style="text-align:center;">
                <div class="col-md-1" >   @item.id</div>
                <div class="col-md-3">@item.CreatedAt</div>
                <div class="col-md-3">@item.Amount</div>
                <div class="col-md-3">
                    @switch (item.Status)
                    {
                        case 0:
                            <label class="text-danger"> Đã hủy</label>
                            break;
                        case 1:
                            <label class="text-info"> Đang chờ</label>
                            break;
                        case 2:
                            <label class="text-info"> Đã xác nhận</label>
                            break;
                        case 3:
                            <label class="text-info"> Đang vận chuyển</label>
                            break;
                        case 4:
                            <label class="text-success"> Thành công</label>
                            break;
                        case 11:
                            <label class="text-info"> Đang chờ</label> <label class="text-success"> (Đã thanh toán bằng VNPay)</label>

                            break;
                        case 12:
                            <label class="text-info"> Đã xác nhận</label> <label class="text-success"> (Đã thanh toán bằng VNPay)</label>
                            break;
                        case 13:
                            <label class="text-info"> Đang vận chuyển</label> <label class="text-success"> (Đã thanh toán bằng VNPay)</label>
                            break;
                    }
                </div>

                <div class="col-md-2" style="text-align:left;">
                    <a class="accordion-collapse collapse show col-md-4" href="#commmentreply-@item.id" data-bs-toggle="collapse" aria-expanded="true" aria-controls="collapse-1">
                        <i class=" fas fa-eye"></i>
                    </a>
                    @if (item.Status==1||item.Status==2)
                {

                    <a href="@Url.Action("HuyDon","Khachhang", new { id = item.id })" class="btn btn-sm btn-danger">
                        <i class="fa"></i>
                        Hủy
                    </a>
                }
                </div>

                <div id="commmentreply-@item.id" class="bg-light p-2 collapse">
                    @foreach (var detail in orderDetailDAO.getList(item.id))
                    {
                        <div class="row">
                            <div class="col-md-1"><img src="~/Public/images/products/@Html.Action("ProductImg","Khachhang", new { productid = detail.ProductId })" class="img-fluid" /></div>
                            <div class="col-md-5">@Html.Action("ProductName", "Khachhang", new { productid = detail.ProductId })</div>
                            <div class="col-md-2">Giá: @string.Format("{0:0,0}", detail.Price)<small class="text-muted">đ</small></div>
                            <div class="col-md-2">Số lượng: @detail.Quantity</div>
                            <div class="col-md-2">Thành tiền: @string.Format("{0:0,0}", detail.Amount)<small class="text-muted">đ</small></div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
</div>

NoiThat/Views/Khachhang/ThongTinCaNhan.cshtml
@model NoiThat.Models.User

@{
    ViewBag.Title = "ThongTinCaNhan";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<section class="section-content bg-white padding-y">
    <div class="container">

        <!-- ============================ ITEM DETAIL ======================== -->
        <div class="row">
            <aside class="col-md-6">
                <div class="card">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <div> <a href="#"><img src="~/Public/images/user/@Model.Img"></a></div>
                        </div>
                    </article>
                </div>
            </aside>
            <main class="col-md-6">
                <article class="product-info-aside">
                    <dl class="row">
                        <dt class="col-sm-3"> Họ và tên</dt>
                        <dd class="col-sm-9">@Model.FullName</dd>

                        <dt class="col-sm-3"> Số điện thoại</dt>
                        <dd class="col-sm-9">@Model.Phone</dd>

                        <dt class="col-sm-3"> Địa chỉ</dt>
                        <dd class="col-sm-9">@Model.Address</dd>

                        <dt class="col-sm-3"> Email</dt>
                        <dd class="col-sm-9">@Model.Email</dd>

                        <dt class="col-sm-3"> Điểm thưởng</dt>
                        <dd class="col-sm-9">@Model.Score điểm</dd>
                    </dl>
                    <a style="background-color:burlywood" href="@Url.Action("ChinhSuaThongTin","Khachhang", new { id = Model.id })" class="btn btn-primary btn-lg">Chỉnh Sửa Thông Tin</a>
                </article>
            </main>
        </div> <!-- row.// -->
        <!-- ================ ITEM DETAIL END .// ================= -->


    </div> <!-- container .//  -->
    

</section>
<style>
    /* Định dạng phần thông tin cá nhân */
    .product-info-aside {
        background-color: #f9f9f9;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
    }

    /* Định dạng các tiêu đề */
    dt {
        font-weight: bold;
        color: #333;
        font-size: 20px; /* Điều chỉnh kích thước chữ */
        font-family: 'Arial', sans-serif; /* Chọn font chữ bạn muốn sử dụng */
    }

    /* Định dạng nội dung */
    dd {
        color: #666;
        margin-bottom: 10px;
        font-size: 18px; /* Điều chỉnh kích thước chữ */
        font-family: 'Arial', sans-serif; /* Chọn font chữ bạn muốn sử dụng */
    }

    /* Định dạng nút chỉnh sửa */
    .btn-primary {
        background-color: #ff6b6b;
        border-color: #ff6b6b;
        color: white;
        font-size: 16px; /* Điều chỉnh kích thước chữ */
        font-family: 'Arial', sans-serif; /* Chọn font chữ bạn muốn sử dụng */
    }

        .btn-primary:hover {
            background-color: #e55d5d;
            border-color: #e55d5d;
        }


    


</style>