NoiThat/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NoiThat.Models
{
    [Table("Posts")]
    public class Post
    {
        [Key]
        public int id { get; set; }

        public int TopicId { get; set; }
        [Required]
        public string Title { get; set; }
        public string Slug { get; set; }
        [Required]
        public string Detail { get; set; }

        [Required]
        public string MetaKey { get; set; }

        [Required]
        public string MetaDes { get; set; }
        public string Img { get; set; }    
        public int? CreatedBy { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int Status { get; set; }
        public string PostType { get; set; }
    }
}

NoiThat/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace NoiThat.Models
{
    [Table("Products")]
    public class Product
    {
        [Key]
        public int id { get; set; }

        public int CatId { get; set; }
        [Required]
        public string Name { get; set; }
        public string Slug { get; set; }
        [Required]
        public string Detail { get; set; }

        [Required]
        public string MetaKey { get; set; }

        [Required]
        public string MetaDes { get; set; }
        public string Img { get; set; }
        public string Origin { get; set; }
        public string Material { get; set; }
        public int? Width { get; set; }
        public int? Length { get; set; }
        public int Number { get; set; }
        public int SupplierId { get; set; }
        public decimal Price { get; set; }
        public decimal PriceSale { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int Status { get; set; }
        public decimal OriginalPrice { get; set; }

    }
}

NoiThat/Controllers/SiteController.cs
using NoiThat.DAO;
using NoiThat.Models;
using NoiThat.Public.common;
using PagedList;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing.Printing;
using System.Linq;
using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.HtmlControls;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Xml.Linq;

namespace NoiThat.Controllers
{
    public class SiteController : Controller
    {
        RateDAO rateDAO = new RateDAO();
        LinkDAO linkDAO = new LinkDAO();
        ProductDAO productDAO = new ProductDAO();
        PostDAO postDAO = new PostDAO();
        CategoryDAO categoryDAO = new CategoryDAO();
        SupplierDAO supplierDAO = new SupplierDAO();
        TopicDAO topicDAO = new TopicDAO();
        CommentDAO commentDAO = new CommentDAO();

        public ActionResult Index(string slug = null, int? page = null)
        {
            if (slug == null)
            {
                //trang chu, ko viet code
                return this.Home();
            }
            else
            {
                //tim slug co trong bang link
                Link link = linkDAO.getRow(slug);
                if (link != null)
                {
                    //slug co trong bang link
                    string typelink = link.TypeLink;
                    switch (typelink)
                    {
                        case "category":
                            {
                                return this.ProductCategory(slug, page);
                            }
                        case "topic":
                            {
                                return this.PostTopic(slug, page);

                            }
                        case "page":
                            {
                                return this.PostPage(slug);
                            }

                        default:
                            {
                                return this.Error404(slug);

                            }
                    }
                }
                else
                {
                    Product p = productDAO.getRow(slug);

                    if (p != null)
                    {
                        ProductInfo productInfo = new ProductInfo();
                        productInfo.CatId = p.CatId;
                        productInfo.id = p.id;
                        productInfo.Name = p.Name;
                        productInfo.Slug = p.Slug;
                        productInfo.Detail = p.Detail;
                        productInfo.MetaKey = p.MetaKey;
                        productInfo.MetaDes = p.MetaDes;
                        productInfo.Img = p.Img;
                        productInfo.Number = p.Number;
                        productInfo.Price = p.Price;
                        productInfo.PriceSale = p.PriceSale;
                        productInfo.SupplierId = p.SupplierId;
                        productInfo.CreatedBy = p.CreatedBy;
                        productInfo.CreatedAt = p.CreatedAt;
                        productInfo.UpdatedBy = p.UpdatedBy;
                        productInfo.UpdatedAt = p.UpdatedAt;
                        productInfo.Status = p.Status;
                        productInfo.Origin = p.Origin;
                        productInfo.Material = p.Material;
                        productInfo.Width = p.Width;
                        productInfo.Length = p.Length;
                        productInfo.CatName = categoryDAO.getRow(productInfo.CatId).Name;
                        productInfo.SupName = supplierDAO.getRow(productInfo.SupplierId).Name;
                        return this.ProductDetail(productInfo);
                    }
                    else
                    {
                        Post post = postDAO.getRow(slug, "post");
                        if (post != null)
                        {
                            return this.PostDetail(post);
                        }
                        else
                        {

                            return this.Error404(slug);
                        }
                    }
                    //slug ko co trong bang link
                }
            }
        }

        public ActionResult Home()
        {
            List<Category> list = categoryDAO.getListByParentId(0);
            return View("Home", list);
        }
        public ActionResult HomeProduct(int id)
        {
            Category category = categoryDAO.getRow(id);
            ViewBag.Category = category;

            //Danh muc theo loai cap 3
            List<int> listcatid = new List<int>();
            listcatid.Add(id);//cap1
            List<Category> listcat2 = categoryDAO.getListByParentId(id);
            if (listcat2.Count() != 0)
            {
                foreach (var cate2 in listcat2)
                {
                    listcatid.Add(cate2.id);//Cap 2
                    List<Category> listcat3 = categoryDAO.getListByParentId(cate2.id);
                    if (listcat3.Count() != 0)
                    {
                        foreach (var cate3 in listcat3)
                        {
                            listcatid.Add(cate3.id);//Cap 3
                        }
                    }
                }
            }
            List<ProductInfo> list = productDAO.getListListByCatId(listcatid, 8);
            return View("HomeProduct", list);
        }


        //nhom action product
        public ActionResult Product(int? page)
        {
            int pageNumber = page ?? 1; //trang hiện tại
            int pageSize = 5; //Số mẫu tin hiển thị trên 1 trang

            IPagedList<ProductInfo> list = productDAO.getList(pageSize, pageNumber);
            ViewBag.Sotrang = 5;
            return View("Product", list);
        }
        public ActionResult ProductCategory(string slug, int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 5;

            Category category = categoryDAO.getRow(slug);
            ViewBag.Category = category;

            //Danh muc theo loai cap 3
            List<int> listcatid = new List<int>();
            listcatid.Add(category.id);//cap1
            List<Category> listcat2 = categoryDAO.getListByParentId(category.id);
            if (listcat2.Count() != 0)
            {
                foreach (var cate2 in listcat2)
                {
                    listcatid.Add(cate2.id);//Cap 2
                    List<Category> listcat3 = categoryDAO.getListByParentId(cate2.id);
                    if (listcat3.Count() != 0)
                    {
                        foreach (var cate3 in listcat3)
                        {
                            listcatid.Add(cate3.id);//Cap 3
                        }
                    }
                }
            }
            IPagedList<ProductInfo> list = productDAO.getListListByCatId(listcatid, pageSize, pageNumber);
            return View("ProductCategory", list);
        }

        public ActionResult ProductSearch(string slug, int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 5;

            // Logic lấy thông tin danh mục dựa trên slug
            Category category = categoryDAO.getRow(slug);
            ViewBag.Category = category;

            // Tạo danh sách ID danh mục cần tìm kiếm
            List<int> listcatid = new List<int>();
            listcatid.Add(category.id); // Thêm danh mục cấp 1

            // Lấy danh sách danh mục cấp 2 và cấp 3 để thêm vào danh sách cần tìm kiếm
            List<Category> listcat2 = categoryDAO.getListByParentId(category.id);
            foreach (var cate2 in listcat2)
            {
                listcatid.Add(cate2.id); // Thêm danh mục cấp 2
                List<Category> listcat3 = categoryDAO.getListByParentId(cate2.id);
                foreach (var cate3 in listcat3)
                {
                    listcatid.Add(cate3.id); // Thêm danh mục cấp 3
                }
            }

            // Lấy danh sách sản phẩm dựa trên danh mục đã chọn
            IPagedList<ProductInfo> list = productDAO.getListListByCatId(listcatid, pageSize, pageNumber);

            // Trả về view "ProductCategory" với danh sách sản phẩm được lấy ra
            return View("ProductCategory", list);
        }


        public ActionResult ProductDetail(ProductInfo product)
        {
            Random rd = new Random();
            List<Product> listCatId = productDAO.getListByCatId(product.CatId);
            List<Product> listRandom = new List<Product>();
            int dem = 0;
            while (dem < 3)
            {
                Product productRD = listCatId[rd.Next(0, listCatId.Count() - 1)];
                if (productRD.id != product.id)
                {
                    listRandom.Add(productRD);
                    dem++;
                }
            }
            UserLogin userLogin = new UserLogin();
            if (Session["UserCustomer"] != "")
            {
                userLogin.UserID = int.Parse(Session["UserId"].ToString());
                userLogin.UserName = Session["FullName"].ToString();
            }

            ViewBag.UserID = userLogin.UserID;


            ViewBag.ListComment = new CommentDAO().ListCommentInfo(0, product.id);

            ViewBag.Product = listRandom;
            return View("ProductDetail", product);
        }


        [ChildActionOnly]
        public ActionResult _ChildComment(int parentid, int productid)
        {
            var data = new CommentDAO().ListCommentInfo(parentid, productid);
            UserLogin userLogin = new UserLogin();
            if (Session["UserCustomer"] != "")
            {
                userLogin.UserID = int.Parse(Session["UserId"].ToString());
                userLogin.UserName = Session["FullName"].ToString();
            }
            for (int k = 0; k < data.Count; k++)

NoiThat/Views/Site/Error404.cshtml
@{
    ViewBag.Title = "Error404";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<h2>Error404</h2>

NoiThat/Views/Site/Home.cshtml
@model IEnumerable<NoiThat.Models.Category>
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

@section header{
    <link href="~/Public/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Public/js/style.css" rel="stylesheet" />
}

<div class="container">
    @*========================= SECTION MAIN  =========================*@
    <section class="section-main padding-y">


        @Html.Action("Slideshow", "Module")

    </section>

    @*========================= SECTION MAIN END// =========================*@
    @*=============== SECTION 1 ===============*@
    <section class="padding-bottom">
        @foreach (var category in Model)
        {
            @Html.Action("HomeProduct", "Site", new { @id = category.id })

        }

        <div style=" width: 100%; margin-left: auto; margin-right: auto;" class="row">
            <div class="col text-center">
                <div style="font-family: 'Montserrat', sans-serif; padding: 40px; perspective: 1000px;">
                    <h1 style="font-family: 'Felix Titling' ;font-size: 3em; color: #343a40; font-weight: bold; letter-spacing: 3px; text-transform: uppercase; transform: rotateX(25deg); transition: transform 0.5s;">Our New Design</h1>
                </div>
            </div>
        </div>


        <div style="margin-top: 10px; width: 1420px; margin-left: auto; margin-right: auto; " id="slider" class="carousel slide" data-ride="carousel">

            <ul class="carousel-indicators">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                <li data-target="#demo" data-slide-to="1"></li>
                <li data-target="#demo" data-slide-to="2"></li>
                <li data-target="#demo" data-slide-to="3"></li>
                <li data-target="#demo" data-slide-to="4"></li>
                <li data-target="#demo" data-slide-to="5"></li>
            </ul>

            <div class="carousel-inner" style="border-radius: 20px;">
                <div class="carousel-item active">
                    <img src="~/Content/images/Pic/new-1.jpg" class="d-block w-100" alt="">
                </div>
                <div class="carousel-item">
                    <img src="~/Content/images/Pic/new-2.jpg" class="d-block w-100" alt="">
                </div>
                <div class="carousel-item">
                    <img src="~/Content/images/Pic/new-3.jpg" class="d-block w-100" alt="">
                </div>
                <div class="carousel-item">
                    <img src="~/Content/images/Pic/new-4.jpg" class="d-block w-100" alt="">
                </div>
                <div class="carousel-item">
                    <img src="~/Content/images/Pic/new-5.jpg" class="d-block w-100" alt="">
                </div>
                <div class="carousel-item">
                    <img src="~/Content/images/Pic/new-6.jpg" class="d-block w-100" alt="">
                </div>
            </div>


            <a class="carousel-control-prev" href="#slider" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#slider" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>


    </section>

</div>
@section scripts{
    <style>
        h1:hover {
            transform: rotateX(0deg);
        }

        .carousel-indicators li:hover {
            opacity: 0.7; /* Thay đổi độ trong suốt khi hover */
        }
    </style>

    <!-- Kích hoạt chức năng tự động trượt qua các ảnh của carousel -->
    <script>
        $(document).ready(function () {
            $('#slider').carousel({
                interval: 3000 // Thời gian trì hoãn giữa các slide, ở đây là 3 giây
            });
        });
    </script>
}

@*container end.//*@

NoiThat/Views/Site/HomeProduct.cshtml
@model IEnumerable<NoiThat.Models.ProductInfo>

@{
    var cat = ViewBag.Category;
}

@{
    Layout = null;
}

@using NoiThat.Library;
@if (Model.Count() != 0)
{

    <header class="section-heading heading-line">
        <h4 class="title-section text-uppercase">@cat.Name</h4>
    </header>

    <div class="card card-home-category">
        <div class="row no-gutters">
            <div class="col-md-3">

                <div class="home-category-banner ">
                    <h5 class="title">@cat.MetaKey</h5>
                    <p>@cat.MetaDes </p>
                    <a href="~/@cat.Slug" class="btn btn-outline-primary rounded-pill">Xem ngay</a>
                    <img src="~/Public/images/categorys/@cat.Img" class="img-bg">
                </div>

            </div> <!-- col.// -->


            <div class="col-md-9">
                <ul class="row no-gutters bordered-cols">

                    @foreach (var product in Model)
                    {

                        <li class="col-6 col-lg-3 col-md-4">
                            <a href="~/@product.Slug" class="item">
                                <div class="card-body">
                                    <h6 class="title"> @product.Name </h6>
                                    <img class="img-sm float-right" src="~/Public/images/products/@product.Img">
                                    <p class="text-muted"><i class="fa fa-shopping-cart"></i> @XString.StrLimit(product.MetaDes, 100)</p>
                                </div>
                            </a>
                        </li>

                    }

                </ul>
            </div> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->

}

NoiThat/Views/Site/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<h2>aaaaaa</h2>

NoiThat/Views/Site/Livingroom.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/css/foot.css">
    <title>Animated Flex Cards</title>
</head>
<body>
    <div class="wrapper">
        <div class="container">
            <input type="radio" name="slide" id="c1" checked>
            <label for="c1" class="card">
                <div class="row">
                    <div class="icon">1</div>
                    <div class="description">
                        <h4>Winter</h4>
                        <p>
                            Winter has so much to offer -
                            creative activities
                        </p>
                    </div>
                </div>
            </label>
            <input type="radio" name="slide" id="c2">
            <label for="c2" class="card">
                <div class="row">
                    <div class="icon">2</div>
                    <div class="description">
                        <h4>Digital Technology</h4>
                        <p>
                            Gets better every day -
                            stay tuned
                        </p>
                    </div>
                </div>
            </label>
            <input type="radio" name="slide" id="c3">
            <label for="c3" class="card">
                <div class="row">
                    <div class="icon">3</div>
                    <div class="description">
                        <h4>Globalization</h4>
                        <p>Help people all over the world</p>
                    </div>
                </div>
            </label>
            <input type="radio" name="slide" id="c4">
            <label for="c4" class="card">
                <div class="row">
                    <div class="icon">4</div>
                    <div class="description">
                        <h4>New technologies</h4>
                        <p>
                            Space engineering becomes
                            more and more advanced
                        </p>
                    </div>
                </div>
            </label>
        </div>
    </div>
</body>
</html>

NoiThat/Views/Site/Post.cshtml
@model IEnumerable<NoiThat.Models.PostInfo>
@{
    ViewBag.Title = "Post";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<section class="section-content padding-y">
    <div class="container">

        <div class="card mb-3">
            <div class="card-body">
                <ol class="breadcrumb float-left">
                    <li class="breadcrumb-item"><a href="@Url.Action("")">Home</a></li>
                    <li class="breadcrumb-item"><a href="~/tat-ca-bai-viet">Tất cả bài viết</a></li>
                </ol>
            </div> <!-- card-body .// -->
        </div> <!-- card.// -->
        @foreach (var post in Model)
        {
            <article class="card card-product-list">
                <div class="row no-gutters">
                    <aside class="col-md-3">
                        <a href="~/@post.Slug" class="img-wrap">
                            @{
                                DateTime date = DateTime.Now;
                            }
                            @if (post.CreatedAt.Value.Day - date.Day <= 7)
                            {
                                <span class="badge badge-danger"> NEW</span>
                            }
                            <img class="img-sm float-right" src="~/Public/images/posts/@post.Img">
                        </a>
                    </aside> <!-- col.// -->
                    <div class="col-md-6">
                        <div class="info-main">
                            <a href="~/@post.Slug" class="h5 title"> @post.Title</a>
                            <p>
                                @NoiThat.Library.XString.StrLimit(post.Detail, 300)
                            </p>


                        </div> <!-- info-main.// -->


                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </article> <!-- card-product .// -->
        }

    </div> <!-- container .//  -->
</section>
<style>
    /* Định dạng breadcrumb */
    .breadcrumb {
        background-color: transparent;
        padding: 0;
        margin: 0;
        font-size: 14px;
    }

    .breadcrumb-item a {
        text-decoration: none;
        color: #333;
        transition: color 0.3s ease;
    }

        .breadcrumb-item a:hover {
            color: #007bff; /* Màu khi hover */
        }

    /* Định dạng danh sách bài viết */
    /* Định dạng danh sách bài viết */
    .section-content {
        padding: 40px 0;
    }

    .card-product-list {
        margin-bottom: 30px;
        border: 1px solid #ddd;
        border-radius: 5px;
        overflow: hidden;
        transition: box-shadow 0.3s ease; /* Thêm hiệu ứng khi hover */
    }

        .card-product-list:hover {
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1); /* Hiệu ứng khi hover */
        }

        .card-product-list .img-wrap {
            position: relative;
            display: block;
            overflow: hidden;
            max-height: 180px; /* Tăng kích thước ảnh */
        }

            .card-product-list .img-wrap img {
                width: 100%;
                height: auto;
                transition: transform 0.3s ease;
            }

            .card-product-list .img-wrap:hover img {
                transform: scale(1.05); /* Hiệu ứng scale khi hover */
            }

    .info-main {
        padding: 15px;
    }

        .info-main .title {
            font-size: 20px; /* Tăng kích thước tiêu đề */
            font-weight: bold;
            color: #333;
            text-decoration: none;
            transition: color 0.3s ease;
            margin-bottom: 10px; /* Cân đối khoảng cách */
        }

            .info-main .title:hover {
                color: #007bff; /* Màu khi hover */
            }

        .info-main p {
            font-size: 16px;
            color: #666;
            line-height: 1.8; /* Tăng độ dài dòng */
            margin-bottom: 15px; /* Cân đối khoảng cách */
        }


</style>

NoiThat/Views/Site/ProductCategory.cshtml
@model PagedList.IPagedList<NoiThat.Models.ProductInfo>

@{
    var category = ViewBag.Category;
}
@using PagedList.Mvc;
@using NoiThat.DAO;
@{ RateDAO rateDAO = new RateDAO();}


@{
    ViewBag.Title = category.Name;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">


        <!-- ============================  FILTER TOP  ================================= -->
        <div class="card mb-3">
            <div class="card-body">
                <ol class="breadcrumb float-left">
                    <li class="breadcrumb-item"><a href="@Url.Action("")">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">@category.Name</a></li>
                </ol>
            </div> <!-- card-body .// -->
        </div> <!-- card.// -->
        <!-- ============================ FILTER TOP END.// ================================= -->


        <div class="row">
            <aside class="col-md-2">
                @Html.Action("ListCategory", "Module")

            </aside> <!-- col.// -->
            <main class="col-md-10">
                @foreach (var product in Model)
                {
                    <article class="card card-product-list">
                        <div class="row no-gutters">
                            <aside class="col-md-3">
                                <a href="~/@product.Slug" class="img-wrap">
                                    @{
                                        DateTime date = DateTime.Now;
                                    }
                                    @if (product.CreatedAt.Value.Day - date.Day <= 7)
                                    {
                                        <span class="badge badge-danger"> NEW</span>
                                    }
                                    <img class="img-sm float-right" src="~/Public/images/products/@product.Img">
                                </a>
                            </aside> <!-- col.// -->
                            <div class="col-md-6">
                                <div class="info-main">
                                    <a href="~/@product.Slug" class="h5 title"> @product.Name</a>
                                    @{ int sosao = (int)Math.Round(rateDAO.AvarageRate(product.id));
                                        if (sosao == 0)
                                        {
                                            <p>(Chưa có đánh giá)</p>
                                        }
                                        else
                                        {
                                            <ul class="rating-stars">
                                                <li style="width:100%" class="stars-active">
                                                    @for (int i = 1; i <= sosao; i++)
                                                    {
                                                        <i class="fa fa-star"></i>
                                                    }
                                                </li>
                                                <li>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </li>
                                            </ul>

                                        }}
                                    <p class="mb-3">
                                        @{ OrderDetailDAO orderDetailDAO = new OrderDetailDAO();}
                                        @{ int soluotmua = orderDetailDAO.SoLuotMua(product.id);}
                                        <span class="tag"> <i class="fa fa-check"></i> Verified</span>
                                        <span class="tag"> @soluotmua người đã mua sản phẩm</span>
                                        <span class="tag"> Xuất xứ từ @product.Origin </span>
                                    </p>
                                    <p>
                                        @product.Detail
                                    </p>
                                </div> <!-- info-main.// -->
                            </div> <!-- col.// -->
                            <aside class="col-sm-3">
                                <div class="info-aside">
                                    <div class="price-wrap">
                                        <del>
                                            <span class="h5 pric text-danger">@string.Format("{0:0,0}", product.PriceSale)</span>
                                        </del>
                                        <small class="text-muted">đ</small>
                                    </div> <!-- price-wrap.// -->
                                    <div class="price-wrap">

                                        <span class="h5 pric text-danger">@string.Format("{0:0,0}", product.Price)</span>
                                        <small class="text-muted">đ</small>
                                    </div> <!-- price-wrap.// -->

                                    <p class="mt-3">
                                        <a href="@Url.Action("CartAdd","GioHang", new {productId=product.id})" class="btn btn-outline-primary"> <i class="fa fa-shopping-cart"></i> Thêm vào giỏ hàng </a>
                                    </p>



                                </div> <!-- info-aside.// -->
                            </aside> <!-- col.// -->
                        </div> <!-- row.// -->
                    </article> <!-- card-product .// -->
                }

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        @for (int i = 1; i <= ViewBag.Sotrang; i++)
                        {
                            <li class="page-item"><a class="page-link" href="~/@category.Slug?page=@i">@i</a></li>

                        }
                    </ul>
                </nav>


                <nav class="mb-4" aria-label="Page navigation sample">
                    <ul class="pagination">
                        @Html.PagedListPager(Model, page => Url.Action("Index", "Site", new { page }))

                    </ul>
                </nav>

            </main> <!-- col.// -->

        </div>

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->